# Generated by Django 3.1.7 on 2021-04-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210402_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='timestap',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
