# Generated by Django 3.1.7 on 2021-03-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210401_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(default='Null', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(),
        ),
    ]
