# Generated by Django 3.1.7 on 2021-04-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='description',
        ),
    ]
