# Generated by Django 3.1.7 on 2021-04-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_remove_branch_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='branch',
        ),
    ]
