# Generated by Django 3.1.7 on 2021-04-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_remove_semester_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
