# Generated by Django 3.1.7 on 2021-04-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_branch_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='papers.branch'),
        ),
    ]
